PAM tests: Login is now blocked in account phase
Previously
https://github.com/pyllyukko/harden.yml/blob/master/files/pam-configs/uid_ge_1000.new
handled it in authentication phase, but because of #89. Now it is being
handled in account phase by pam_access.

diff --git a/.github/workflows/pam.yml b/.github/workflows/pam.yml
--- a/.github/workflows/pam.yml
+++ b/.github/workflows/pam.yml
@@ -25,6 +25,8 @@ jobs:
           # Unknown services
           # TODO: authenticate & chauthtok
           for operation in acct_mgmt open_session; do pamtester nonexistent nobody "${operation}" || exit 1; done
+          # Login for random users
+          pamtester login nobody acct_mgmt || exit 1
       - name: Run Ansible playbook for pam
         run: ansible-playbook harden.yml --tags pam --skip-tags slackware,centos
       - name: Test post-harden
@@ -41,6 +43,8 @@ jobs:
           pamtester su nobody authenticate && { echo -e '[\033[1;31m-\033[0m] Test 4 failed' 1>&2; exit 1; }
           # Unknown services should be denied by /etc/pam.d/other
           for operation in authenticate acct_mgmt chauthtok open_session; do echo "[*] Testing nonexistent service operation ${operation}"; pamtester nonexistent nobody "${operation}" && exit 1; done; true
+          # Random users should not be able to login
+          pamtester login nobody acct_mgmt && { echo -e '[\033[1;31m-\033[0m] Test 5 failed' 1>&2; exit 1; }
   libpamtest:
     runs-on: ubuntu-latest
     steps:
@@ -119,10 +123,10 @@ jobs:
           # PAM_PERM_DENIED
           echo '[*] Test 5 - nobody cron:account'
           sudo tests/test -t 5 -r 6
-          # Login for "nobody" should be blocked by hardened configuration even with a valid password
-          # PAM_AUTH_ERR
-          echo '[*] Test 6 - nobody login:auth'
-          sudo tests/test -t 6 -r 7
+          # Login for "nobody" was previously blocked by https://github.com/pyllyukko/harden.yml/blob/master/files/pam-configs/uid_ge_1000.new
+          # Now it is handled in account phase by pam_access. So the authentication itself will succeed, but access is denied.
+          #echo '[*] Test 6 - nobody login:auth'
+          #sudo tests/test -t 6 -r 7
           # Use of su should be denied
           # PAM_PERM_DENIED
           echo '[*] Test 7 - nobody su:auth'
